from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors


def generate_fir_pdf(*, fir_number, filed_at, filed_by, employee_id, department,
                     complainant_name, incident_type, incident_date, location, description):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("TitleCenter", parent=styles["Title"], alignment=TA_CENTER, spaceAfter=12)
    small = ParagraphStyle("Small", parent=styles["BodyText"], fontSize=8.5, leading=11)
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=9.5, leading=13)

    def p(value, style=body):
        value = str(value or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return Paragraph(value.replace("\n", "<br/>"), style)

    story = [
        p("SECURE DMS — FIRST INFORMATION REPORT", title),
        p("Official digital filing record", small),
        Spacer(1, 12),
    ]
    data = [
        [p("FIR Number", small), p(fir_number, small)],
        [p("Filed At (UTC)", small), p(filed_at, small)],
        [p("Department", small), p(department, small)],
        [p("Filed By", small), p(f"{filed_by} ({employee_id})", small)],
        [p("Complainant", small), p(complainant_name, small)],
        [p("Incident Type", small), p(incident_type, small)],
        [p("Incident Date", small), p(incident_date, small)],
        [p("Location", small), p(location, small)],
    ]
    table = Table(data, colWidths=[125, 365])
    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.whitesmoke),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 7),
        ("RIGHTPADDING", (0,0), (-1,-1), 7),
        ("TOPPADDING", (0,0), (-1,-1), 7),
        ("BOTTOMPADDING", (0,0), (-1,-1), 7),
    ]))
    story += [table, Spacer(1, 14), p("<b>Description</b>"), p(description), Spacer(1, 25)]
    story += [
        p("Digital filing record", small),
        p("This FIR was generated by Secure DMS from the submitted form. The final PDF bytes are SHA-256 hashed and digitally signed with the filing user's RSA-PSS-SHA256 private key.", small),
    ]
    doc.build(story)
    return buf.getvalue()
